### ISSUE TITLE
Localize app

### ISSUE THREAD

**Issue by jermanuts** [niedev/RTranslator#10]
Thanks for developing this amazing app, is there a way to translated the app itself using https://weblate.org/en/. Also, does this app support RTL direction?

**Comment by niedev** [comment]
Thank you!  For now the app has only been localized in English and Italian (the only languages I know), I currently don't have the money to pay for translators (which would also be needed with Weblate from what I understand), and I don't think the machine translation tools are reliable enough for app translation (I know my app does just that 😂 but for conversations you don't need that much precision). As for RTL, it's not supported yet but it's one of the things I will definitely implement in the future.

**Comment by jermanuts** [comment]
> I currently don't have the money to pay for translators (which would also be needed with Weblate from what I understand)

No you don't, Weblate can host your app's components if it is Libre for free, you can contact them for more info if you need.

**Comment by niedev** [comment]
I will, thank you!

**Comment by jermanuts** [comment]
hello @niedev can you point me to changes done? Weblate org account has been setup or other ways for translation process?

**Comment by niedev** [comment]
> hello @niedev can you point me to changes done? Weblate org account has been setup or other ways for translation process?

Hi, I got better informed and saw that obviously weblate doesn't offer human translators for free, but if I wanted in my case I could use the translation suggestion feature to have the community do the translations, I'll definitely take this into consideration for the future, but for now I'm the only maintainer of the repository and I don't work on the app full time, so for now I don't have time to deal with secondary things (the app is still usable even if you don't know English), I prefer to focus on fixing bugs and improving the functionality of the app.

But sooner or later I will also think about the localization, and at that point this tool could be very useful to me, so thank you!
