### ISSUE TITLE
Sideloading of all components (onnx files)?

### ISSUE THREAD

**Issue by 3dluvr** [niedev/RTranslator#16]
Hi,

Would you please provide instructions, or a method, for sideloading of the components (onnx files) in an off-line mode, so that the app does not have to automatically download them upon first start.

This would most likely benefit everyone, for various reasons such as: lowering mobile data usage, ease of installation on multiple devices, privacy, etc.

Thanks!

**Comment by niedev** [comment]
Hi, thanks for the suggestion, I added this to the list of things to do 👍

**Comment by WeiYoun** [comment]
mobile data and wifi cannot download succesfully，although with proxy

**Comment by fffandpiao** [comment]
I really need the offline download function, but online downloads will get stuck and fail.

**Comment by niedev** [comment]
@WeiYoun @fffandpiao That's strange, have you checked that you have enough space on your phone? (with a good enough margin) If so can you tell me if you are using an sd card and if the apps are configured to be saved there?

**Comment by WeiYoun** [comment]
> @WeiYoun @fffandpiao That's strange, have you checked that you have enough space on your phone? (with a good enough margin) If so can you tell me if you are using an sd card and if the apps are configured to be saved there?

there are enough space to store（about 70G），and has permission to save，many times when download *head.onnx failed.

**Comment by niedev** [comment]
> > @WeiYoun @fffandpiao That's strange, have you checked that you have enough space on your phone? (with a good enough margin) If so can you tell me if you are using an sd card and if the apps are configured to be saved there?
> 
> there are enough space to store（about 70G），and has permission to save，many times when download *head.onnx failed.

You are using an sd card? The apps are configured to be saved there?

**Comment by fffandpiao** [comment]
> @WeiYoun @fffandpiao这很奇怪，你检查过你的手机是否有足够的空间吗？（有足够的余地）如果是的话，你能告诉我你是否使用了 SD 卡以及应用程序是否配置为保存在那里吗？

I downloaded successfully. Every time I downloaded a package, it would get stuck. I thought it was unresponsive. It took a long time to download online.

**Comment by niedev** [comment]
@fffandpiao if you have an sdcard and have it set to hold app data, that might have been the problem, since I'm currently using Android's downloadManager for downloads, and it can't save files directly to the app's internal storage, so I download them to external storage and then move them to the app's internal storage, normally this process happens instantly, but if you use an sdcard configured as I said above, the transfer takes quite a while.

Or maybe the download is slow for [this ](https://www.reddit.com/r/China/comments/v8fv0p/why_is_github_so_slow_in_china_recently/) reason (my models are saved on Github, so the download is done from there)

**Comment by niedev** [comment]
The [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.3) that supports sideloading is out 😁, and the guide for sideloading is [here](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md), let me know how it works.

**Comment by 3dluvr** [comment]
I can confirm that the app is successfully sideloading the local models, when dropped in the appropriate folder per the guide.

You are awesome, thank you!
