### ISSUE TITLE
Exit Button

### ISSUE THREAD

**Issue by sadtler** [niedev/RTranslator#17]
Sometimes I want it to not run in the background when in close it, which is always.

This is a beautiful application, I wish I did not need to kill it to exit fully.

**Comment by niedev** [comment]
Thank you. When you are in WalkieTalkie or Conversation mode and press the home button these will continue to run in the background, but only when you are in those two screens, to avoid this and exit either mode correctly just press the back button and go back to the text translation mode (or the pairing screen) and then press the home button.
