### ISSUE TITLE
Submit in F-Droid

### ISSUE THREAD

**Issue by TheEvilSkeleton** [niedev/RTranslator#2]
Any chance this app can be submitted in F-Droid?

**Comment by niedev** [comment]
I'm working on it, I think I'll publish it in a few days

**Comment by niedev** [comment]
I read the inclusion policy of F-Droid and unfortunately I cannot include it because the apps in F-Droid must be completely open-source, even the libraries, and the Google APIs are not open-source

**Comment by TheEvilSkeleton** [comment]
Bummer. I would've loved to see this app in F-Droid.

**Comment by the4anoni** [comment]
Since Google APIs are removed can new RTranslator be published to F-Droid?

**Comment by se7en-x230** [comment]
F-Droid would be amazing agreed
