### ISSUE TITLE
will support for dialects?e.g. hokkien

### ISSUE THREAD

**Issue by jackylee1** [niedev/RTranslator#21]
will support for dialects?e.g. hokkien

**Comment by niedev** [comment]
It will depend on the new AI models that I will add in the future, for now dialects cannot be specified for Whisper and NLLB, but some dialects are still recognized (only if the translation takes place for those dialects into another language obviously) when the language from which dialects derive is selected. 

In your case you could try setting Chinese as the input language. Let me know if it works
