### ISSUE TITLE
什么时候有ios版？

### ISSUE THREAD

**Issue by KDCJT** [niedev/RTranslator#22]
什么时候有ios版？真的很需要

**Comment by niedev** [comment]
An iOS version is not planned for now, developing and maintaining two versions of RTranslator for two different platforms is too demanding for a side-project, but if the project continues to grow to the point where I can work on it full time or have employees, I will definitely do it.

**Comment by KDCJT** [comment]
感谢回答，软件很棒

**Comment by niedev** [comment]
Thank you!

**Comment by sampan79** [comment]
> An iOS version is not planned for now, developing and maintaining two versions of RTranslator for two different platforms is too demanding for a side-project, but if the project continues to grow to the point where I can work on it full time or have employees, I will definitely do it.

Thank you for your reply.
