### ISSUE TITLE
Tts should be installed, why not tip?

### ISSUE THREAD

**Issue by purezhang** [niedev/RTranslator#28]
![Screenshot_20240625_231251](https://github.com/niedev/RTranslator/assets/10355305/d9aa32f6-7255-4d80-8568-69e1da89a823)
![Screenshot_20240625_232407](https://github.com/niedev/RTranslator/assets/10355305/dedccd3e-74c4-4c4d-8659-f679933300ea)

Tts should be installed, why not tip?

**Comment by niedev** [comment]
As discussed [here](https://github.com/niedev/RTranslator/issues/8), on some devices the TTS doesn't work (even Google's one), I don't know why but when I have time I will install on my phone some of the custom ROMs that have this issue to investigate (or I will add an integrated TTS to RTranslator), for now, the only thing you can do is clicking on continue and use RTranslator without TTS.

**Comment by fishergz** [comment]
My Xiaomi 10 also encountered this error before. After installing Google TTS, it still didn't work. Then, after switching back to the system's built-in TTS, it returned to work ok.

**Comment by niedev** [comment]
> My Xiaomi 10 also encountered this error before. After installing Google TTS, it still didn't work. Then, after switching back to the system's built-in TTS, it returned to work ok.

For now the only TTS supported is the Google one (there's actually a check in the code to make sure you're using Google TTS, it doesn't even matter what TTS you select, the Google TTS will be used if you have installed), so probably the TTS wasn't working at the beginning because a restart of RTranslator was needed.

**Comment by starlightjy** [comment]
@niedev 
Hello niedev, I have found the TTS initialization error's reason on these devices include my mobile phone Xiaomi13Ultra powered by Android14, and I have fix it and try it on my phone.
The Apps targeting Android 11 or above that use text-to-speech should declare TTS  in the queries elements of the project manifest("AndroidManifest.xml"):
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"  
    xmlns:tools="http://schemas.android.com/tools">  
    <queries>  
        <intent>  
            <action android:name="android.intent.action.TTS_SERVICE" />  
        </intent>  
    </queries>  
    <!--other original configs-->
</manifest>  
```
![QQ截图20240627214218](https://github.com/niedev/RTranslator/assets/8947443/45691729-3c71-4d08-ac6c-119b3712b52d)

I download the source code and add  these code on  AndroidManifest.xml, build apk and install on my phone, my phone can use tts normal (Of course, we should install Google TTS "Speech Recognition & Synthesis" on GooglePlay first).
Here is the google's document:
[https://developer.android.com/reference/android/speech/tts/TextToSpeech](https://developer.android.com/reference/android/speech/tts/TextToSpeech)

**Comment by niedev** [comment]
Thank you very much @starlightjy! 

The TTS code was 4 years old and I didn't know about this new declaration, also on my phone with Android 14 it worked, but probably the need for this declaration depends on the specific ROM, so it would explain why some had problems and others didn't.

If you want to appear among the contributors of RTranslator, send me a simple pull request with this change, if you don't have the desire/time I can insert it myself and cite you in the new release, let me know.

**Comment by starlightjy** [comment]
I have made a simple pull request. Thanks for your invite!

**Comment by starlightjy** [comment]
> Thank you very much @starlightjy!
> 
> The TTS code was 4 years old and I didn't know about this new declaration, also on my phone with Android 14 it worked, but probably the need for this declaration depends on the specific ROM, so it would explain why some had problems and others didn't.
> 
> If you want to appear among the contributors of RTranslator, send me a simple pull request with this change, if you don't have the desire/time I can insert it myself and cite you in the new release, let me know.

@niedev I have made a simple pull request. Thanks for your invite!

**Comment by niedev** [comment]
There is a [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.2) that should fix the TTS issues! 😁 Let me know if it works correctly.

**Comment by purezhang** [comment]
> My Xiaomi 10 also encountered this error before. After installing Google TTS, it still didn't work. Then, after switching back to the system's built-in TTS, it returned to work ok.

how to do this？
my device is zte-2022P（a30u with myos 13）


> There is a [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.2) that should fix the TTS issues! 😁 Let me know if it works correctly.


Does it still appear not to be working properly? 
Is there anything else I need to do?


![微信图片_20240703171530](https://github.com/niedev/RTranslator/assets/10355305/680f68c9-b5dc-4d0c-953c-dd4724a0f89d)
![微信图片_20240703171628](https://github.com/niedev/RTranslator/assets/10355305/b44b3e0b-c58d-43b2-9146-fc48ce72d78f)
![微信图片_20240703171629](https://github.com/niedev/RTranslator/assets/10355305/0a656e90-3683-462e-8fda-6cf466c5703b)
![微信图片_202407031716291](https://github.com/niedev/RTranslator/assets/10355305/4d15ba21-acbf-4da9-8bbd-7a1f3d502979)
![微信图片_202407031716292](https://github.com/niedev/RTranslator/assets/10355305/0890adf6-e5e3-4d9e-8104-e45da5b89b8c)

**Comment by niedev** [comment]
@purezhang, if you go in the settings of RTranslator -> Text to speech, the Google TTS engine is the one selected?

**Comment by purezhang** [comment]
> @purezhang, if you go in the settings of RTranslator -> Text to speech, the Google TTS engine is the one selected?


https://github.com/niedev/RTranslator/assets/10355305/b5b79cb8-1f84-47c8-a07a-50d8a3002204

**Comment by niedev** [comment]
@purezhang you should click directly on "preferred engine" to select the TTS engine, not in the preferred engine settings icon, nor below (where you only select the TTS language), let me know.

**Comment by starlightjy** [comment]
@purezhang  可以先看看小米手机的系统TTS设置,TTS引擎是否选择正确了.把引擎列表和语音都切换试试看(切换后注意重启应用).
![image](https://github.com/niedev/RTranslator/assets/8947443/f1501797-2a5b-4492-b4dc-f56dcec58d82)

**Comment by purezhang** [comment]
> @purezhang 可以先看看小米手机的系统TTS设置,TTS引擎是否选择正确了.把引擎列表和语音都切换试试看(切换后注意重启应用). ![image](https://private-user-images.githubusercontent.com/8947443/345893445-f1501797-2a5b-4492-b4dc-f56dcec58d82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTQzNzUsIm5iZiI6MTcyMDM1NDA3NSwicGF0aCI6Ii84OTQ3NDQzLzM0NTg5MzQ0NS1mMTUwMTc5Ny0yYTViLTQ0OTItYjRkYy1mNTZkY2VjNThkODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTIwNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzlmNDRkZjZhYjllZGIxMWM0NDZkZGUxMDYzZDAwZjQxYTBiZTVjNzgxNTY3M2RlYWU4NjliNGZiZWJiMmI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IIsipQaYOkd7IE-xa4SODVTVjZbL21Hw_ZMnAyzjXu8)

非常感谢你的回复，我上面视频里面已经展示了我的中兴文字转语音选项，只有一个选项就是“中文”，可以帮我看看我的设置是否正确，谢谢

**Comment by purezhang** [comment]
> @purezhang, if you go in the settings of RTranslator -> Text to speech, the Google TTS engine is the one selected?

如我视频中展示，我的语音转文字选项中 只有一个选项“中文”，没有google tts 等其他选项

As I showed in the video, my voice transcription option has only one option: Chinese language, no other options, etc.

**Comment by starlightjy** [comment]
根据你的视频,下面我发的截图中, 两个红框区域是不一样的点击区域, 你两个红框区域分别点击一下看看是不是有不一样的内容
![QQ截图20240707202042](https://github.com/niedev/RTranslator/assets/8947443/58360420-bae8-46cd-b998-18732bde9a9e)

**Comment by purezhang** [comment]
> @purezhang you should click directly on "preferred engine" to select the TTS engine, not in the preferred engine settings icon, nor below (where you only select the TTS language), let me know.








> 根据你的视频,下面我发的截图中, 两个红框区域是不一样的点击区域, 你两个红框区域分别点击一下看看是不是有不一样的内容 ![QQ截图20240707202042](https://private-user-images.githubusercontent.com/8947443/346334188-58360420-bae8-46cd-b998-18732bde9a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTUzNjQsIm5iZiI6MTcyMDM1NTA2NCwicGF0aCI6Ii84OTQ3NDQzLzM0NjMzNDE4OC01ODM2MDQyMC1iYWU4LTQ2Y2QtYjk5OC0xODczMmJkZTlhOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTIyNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDljNmIyMGE1NTFhMzlhODBhMDUzODk1ZmExOTA1NGQzYjk1MzliMTI3MGMwNTMzNTAwMGFiNjVlZTNhODE2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bEybGSVNPqNR6TIQtMjBBIaMcGkGiQ-JWWgCFjGND04)

是的是的，按我的理解，小米是可以选择首选引擎的，而中兴是不能选择的

我点了齿轮修改之后只有一个选项就是中文

**Comment by niedev** [comment]
@purezhang 

![Screenshot_20240707_143506_Chrome](https://github.com/niedev/RTranslator/assets/32955129/c9068877-b643-4f92-9483-ae324725d33a)

**Comment by starlightjy** [comment]
> > @purezhang you should click directly on "preferred engine" to select the TTS engine, not in the preferred engine settings icon, nor below (where you only select the TTS language), let me know.
> 
> > 根据你的视频,下面我发的截图中, 两个红框区域是不一样的点击区域, 你两个红框区域分别点击一下看看是不是有不一样的内容 ![QQ截图20240707202042](https://private-user-images.githubusercontent.com/8947443/346334188-58360420-bae8-46cd-b998-18732bde9a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTUzNjQsIm5iZiI6MTcyMDM1NTA2NCwicGF0aCI6Ii84OTQ3NDQzLzM0NjMzNDE4OC01ODM2MDQyMC1iYWU4LTQ2Y2QtYjk5OC0xODczMmJkZTlhOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTIyNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDljNmIyMGE1NTFhMzlhODBhMDUzODk1ZmExOTA1NGQzYjk1MzliMTI3MGMwNTMzNTAwMGFiNjVlZTNhODE2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bEybGSVNPqNR6TIQtMjBBIaMcGkGiQ-JWWgCFjGND04)
> 
> 是的是的，按我的理解，小米是可以选择首选引擎的，而中兴是不能选择的
> 
> 我点了齿轮修改之后只有一个选项就是中文

你的中兴手机如果安装了GoogleTTS后,还是没有TTS引擎可以选择、切换的话,估计是特定手机系统代码对该功能做了很大的修改(包括但不限于删除了英文TTS引擎的支持,屏蔽了第三方应用调用系统TTS引擎等等). 这样的问题没有实体机调试,很抱歉我暂时无法帮助定位具体问题来解决了. 
等待后续是否有其他开发者能定位并解决问题.

**Comment by purezhang** [comment]
> > > @purezhang you should click directly on "preferred engine" to select the TTS engine, not in the preferred engine settings icon, nor below (where you only select the TTS language), let me know.
> > 
> > 
> > > 根据你的视频,下面我发的截图中, 两个红框区域是不一样的点击区域, 你两个红框区域分别点击一下看看是不是有不一样的内容 ![QQ截图20240707202042](https://private-user-images.githubusercontent.com/8947443/346334188-58360420-bae8-46cd-b998-18732bde9a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTUzNjQsIm5iZiI6MTcyMDM1NTA2NCwicGF0aCI6Ii84OTQ3NDQzLzM0NjMzNDE4OC01ODM2MDQyMC1iYWU4LTQ2Y2QtYjk5OC0xODczMmJkZTlhOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMTIyNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDljNmIyMGE1NTFhMzlhODBhMDUzODk1ZmExOTA1NGQzYjk1MzliMTI3MGMwNTMzNTAwMGFiNjVlZTNhODE2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bEybGSVNPqNR6TIQtMjBBIaMcGkGiQ-JWWgCFjGND04)
> > 
> > 
> > 是的是的，按我的理解，小米是可以选择首选引擎的，而中兴是不能选择的
> > 我点了齿轮修改之后只有一个选项就是中文
> 
> 你的中兴手机如果安装了GoogleTTS后,还是没有TTS引擎可以选择、切换的话,估计是特定手机系统代码对该功能做了很大的修改(包括但不限于删除了英文TTS引擎的支持,屏蔽了第三方应用调用系统TTS引擎等等). 这样的问题没有实体机调试,很抱歉我暂时无法帮助定位具体问题来解决了. 等待后续是否有其他开发者能定位并解决问题.



> @purezhang
> 
> ![Screenshot_20240707_143506_Chrome](https://private-user-images.githubusercontent.com/32955129/346334956-c9068877-b643-4f92-9483-ae324725d33a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODgzMTYsIm5iZiI6MTcyMTI4ODAxNiwicGF0aCI6Ii8zMjk1NTEyOS8zNDYzMzQ5NTYtYzkwNjg4NzctYjY0My00ZjkyLTk0ODMtYWUzMjQ3MjVkMzNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA3MzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZGU1NmE0NTI2NmNmZWQwZDgyMmJkODYwNmNiNTExZjg0OTExNjM2Y2U2ODkzZTljZjE5NzZlNmExNTRlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lNISIZeSS4--NdBgjL7W4I9RZ4LgtnrwaM5IqA11M0Y)

非常非常感谢🙏
尝试了  niedev 的方法 可以选择了。

最近工作忙出差一直没时间搞。
但是对话模式依然显示无设备

![Screenshot_20240718_153240](https://github.com/user-attachments/assets/059d727e-954b-4eb6-8c58-6237a199b99f)
![Screenshot_20240718_153135](https://github.com/user-attachments/assets/b8845a41-4a95-497f-a705-d60367de0541)
