### ISSUE TITLE
There was an error with the tts initialization, do you want to continuewithout tts?

### ISSUE THREAD

**Issue by xzzcx** [niedev/RTranslator#33]
There was an error with the tts initialization, do you want to continuewithout tts?

**Comment by xzzcx** [comment]
![微信图片_20240627143011](https://github.com/niedev/RTranslator/assets/28998876/b4bc1243-8021-421b-b05b-fbb950a8c1d4)

**Comment by niedev** [comment]
See [here](https://github.com/niedev/RTranslator/issues/8), there is already a discussion about it, I will close this because it is a duplicate.
