### ISSUE TITLE
Would you please add proxy when downloading AI Modules?

### ISSUE THREAD

**Issue by jonozw** [niedev/RTranslator#37]
Some regions can not download AI modules directly at the beginning step. 
Would you please add proxy setting at the first step to allow download AI modules trough proxy? thanks

**Comment by niedev** [comment]
I've never set up a proxy, so I don't know where to start to add settings like this.

But most likely with the future release of RTranslator 2.1, I'll improve the downloads and include the ability to download the models separately and insert them manually into the app (I will also do a tutorial)

**Comment by kyochou** [comment]
I have the same problem, stuck during the process of downloading the model.

**Comment by niedev** [comment]
@jonozw @kyochou The [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.3) that improves the download is out! Let me know if this solves your problem (now you can use [sideloading](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md)).

**Comment by jonozw** [comment]
Hi, niedev

thanks. 

But it still does not work for me. 
Let me explain, in some regions, user can not access website like github, openai directly, we need to use proxy in browser. 
When downloading modules in RT, the APP try to download the modules directly, and can not connect the server. 
So I ask can you add proxy setting in the screen of module download step. 

It is not logic problem, just some of our specila problem.

**Comment by niedev** [comment]
@kyochou but now with [sideloading ](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md) you can download the models using a proxy and then manually insert them into the app, in that case the app takes the models directly from the folder where they were inserted without downloading anything (unless the downloaded files are corrupted due to some error in the download, so if you have done sideloading and it doesn't work it could be for this reason, in this case retrying the download redo the sideloading should solve the problem, remember to reset the app)

**Comment by kyochou** [comment]
> @kyochou but now with [sideloading ](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md) you can download the models using a proxy and then manually insert them into the app, in that case the app takes the models directly from the folder where they were inserted without downloading anything (unless the downloaded files are corrupted due to some error in the download, so if you have done sideloading and it doesn't work it could be for this reason, in this case retrying the download redo the sideloading should solve the problem, remember to reset the app)

I have downloaded the latest version. Now, I can download the model successfully. Thank you for your help.

**Comment by Eyion** [comment]
Even though I used a proxy, the download was still very slow. 
When downloading NLLB, the progress is easily stuck at 0.69GB and 0.93GB, and I don't know later, because my progress is still stuck at 0.93GB.

**Comment by niedev** [comment]
@Eyion have you tried sideloading or you used RTranslator for the download?

**Comment by Eyion** [comment]
I failed to download using RTranslator, then succeeded using sideloading. Using walkie-talkie mode, the voice is robotic and the translation is inaccurate.

**Comment by niedev** [comment]
@Eyion The quality of the voice depends on your system tts (read [this](https://github.com/niedev/RTranslator?tab=readme-ov-file#text-to-speech) for more info on how to change it), the quality of the translation depends on the languages you choose, some have lower translation quality than others (in the future I will improve the translation and speech recognition quality using better models), can you tell me what languages did you used?
