### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by ghost** [niedev/RTranslator#39]
1. Can you add Serbian to language selection list (its very similar language to Croatian)
2. Can you add support for other TTS Engines: k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html

**Comment by niedev** [comment]
1. I have already answered [here](https://github.com/niedev/RTranslator/issues/34)
2. I recently received some pull requests that should make RTranslator compatible with other TTS, I will do the last changes and tests, and in these days a new version of the app compatible with almost all TTS engines should be released.
