### ISSUE TITLE
I've installed it but it doesn't recognize it

### ISSUE THREAD

**Issue by zhl111** [niedev/RTranslator#40]
In this device there iS no google tts engine, download it to be able to use the tts

My phone is Samsung Galaxy s23 ultra

press continue，but it's not running

**Comment by niedev** [comment]
I am aware of this problem and a user (or a hero) have found a solution (see [here](https://github.com/niedev/RTranslator/issues/28)), I'll release an update these days that should fix the problem, and should also support other TTS (thanks to another hero)

**Comment by niedev** [comment]
Anyway it's very strange that it doesn't run after pressing continue, I'll try to understand why. For now, try to reinstall the app.

**Comment by zhl111** [comment]
Download is too slow……Looking forward to your updates

**Comment by zhl111** [comment]
I can use it after I reinstall it, waiting for tts to be recognized

**Comment by niedev** [comment]
There is a [new release](https://github.com/niedev/RTranslator/releases) that should fix the TTS issues! 😁 Let me know if it works correctly.

**Comment by zhl111** [comment]
It worked，wonderful
