### ISSUE TITLE
Repeat translated word/sentences

### ISSUE THREAD

**Issue by se7en-x230** [niedev/RTranslator#43]
For language learning it would be necessary to hit the "speaker" icon to keep repeating the translation.

**Comment by niedev** [comment]
This app was not designed for language learning but for communicating, however in the future a button to read the translation will be added to the text translation mode. As for a similar button for the WalkieTalkie mode, I will evaluate whether to include it 👍

**Comment by se7en-x230** [comment]
Thanks that would be nice also in case you did not here correct the first time .
