### ISSUE TITLE
china use RTranslator error

### ISSUE THREAD

**Issue by happyhuangjinjin** [niedev/RTranslator#45]
"https://github.com/niedev/RTranslator/releases/download/2.0.0/NLLB_cache_initializer.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/NLLB_decoder.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/NLLB_embed_and_lm_head.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/NLLB_encoder.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/Whisper_cache_initializer.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/Whisper_cache_initializer_batch.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/Whisper_decoder.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/Whisper_detokenizer.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/Whisper_encoder.onnx",
"https://github.com/niedev/RTranslator/releases/download/2.0.0/Whisper_initializer.onnx"

代码中这些下载不下来；然后下载下来后，放到自己的服务器，替换成自己的地址；启动后把这个错误：
There was an error loading the files of the models for translation and speech recognition, try restarting the app, if the problem persists then reset it.

另外代码有个 intent.setData(Uri.parse("https://play.google.com/store/apps/details?id=com.google.android.tts"));  连不上谷歌，自己下载一个安装了。china是不是不好使

**Comment by zhl111** [comment]
我直接下载了可以用的，新版本没有问题

**Comment by eix128** [comment]
how these onnx files generated ? we need to fine tune onnx files
