### ISSUE TITLE
 download models

### ISSUE THREAD

**Issue by sunheroxi** [niedev/RTranslator#46]
Using app to download models is too slow. Use the computer to download 10 models in 2.0 and copy them to the corresponding location. Why do you still need to restart downloading models when you open the app?

**Comment by niedev** [comment]
> Why do you still need to restart downloading models when you open the app?

Because the sideloading is not yet supported by the app, but I'm working on it, and in the next few days it will be implemented, with a tutorial explaining how to do it too.

**Comment by niedev** [comment]
@sunheroxi The [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.3) that supports sideloading is out 😁, and the guide for sideloading is [here](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md), let me know how it works.

**Comment by sunheroxi** [comment]
The improvements were quick, dry and beautiful, so we can finally try it.
