### ISSUE TITLE
[Feature request] Material You 3 App icon design

### ISSUE THREAD

**Issue by SpiritOTHawk** [niedev/RTranslator#47]
Thank you for wanting to share an idea! But before starting, ensure to check if this feature request respects the following requirements:
- [ x] It is written in English (I can translate what you say, but issues written in English are easier to read for the other users).
- [ x] There is not already a similar feature request among the open or closed issues.

**Describe the solution you'd like**
For example 
![Screenshot_20240701-132036](https://github.com/niedev/RTranslator/assets/76490476/4891cf84-02da-4ba5-b77f-b0f5b24b4f25)

**Comment by niedev** [comment]
Hi, do you mean support for changing the color of the icon with material you?

**Comment by SpiritOTHawk** [comment]
> Hi, do you mean support for changing the color of the icon with material you?

Hi, yeah.

**Comment by niedev** [comment]
Ok, I will add this to the list of things to do 👍
