### ISSUE TITLE
[Feature request] Can you develop a Windows desktop?

### ISSUE THREAD

**Issue by BlueBlue7891** [niedev/RTranslator#60]
Hello, This project is excellent. can you develop the desktop side?

**Comment by niedev** [comment]
Hi, thank you! I have already answered [here](https://github.com/niedev/RTranslator/issues/14)

**Comment by eix128** [comment]
@BlueBlue7891 
There is cross platform library for that on java...
checkout :
https://github.com/eix128/WhisperJET
