### ISSUE TITLE
[Feature request]Request realtime floating subtitle with translation function for background voice

### ISSUE THREAD

**Issue by vseal001** [niedev/RTranslator#63]
Refer to follows:

<img width="375" alt="unnamed-1" src="https://github.com/user-attachments/assets/3922c449-255e-4207-b479-32e2e9b3d25e">

<img width="375" alt="unnamed" src="https://github.com/user-attachments/assets/06eabf5a-3c89-4e32-9c32-36d5738e99f0">
<img width="375" alt="unnamed" src="https://github.com/user-attachments/assets/20d013d7-05cf-4178-b919-69d2bfbe377c">

**Comment by niedev** [comment]
Thank you for your suggestion, for now the latency of my app is too high for a function of this type, but surely when I will be able to speed up the speech recognition and translation (not so soon) I will try to implement this feature.
