### ISSUE TITLE
[Please Add Hindi Language]

### ISSUE THREAD

**Issue by VKCYBER** [niedev/RTranslator#72]
Thank you for wanting to share an idea! But before starting, ensure to check if this feature request respects the following requirements:
- [x] It is written in English (I can translate what you say, but issues written in English are easier to read for the other users).
- [ ] There is not already a similar feature request among the open or closed issues.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by niedev** [comment]
With RTranslator 2.1 Hindi language is supported, but has low quality, if you want you can use it enabling the "Support low quality languages" setting in the app.
