### ISSUE TITLE
just a thought

### ISSUE THREAD

**Issue by yenerismail** [niedev/RTranslator#75]
Hello, 
For some languages, Google Live transcribe app supports offline language packs. Is there a chance to use this as an option?
good works,

**Comment by niedev** [comment]
Hi, thank you for your suggestion.

Unfortunately, the only way to use Google recognition is through paid APIs that work via cloud (the same ones used for RTranslator 1.0), Google has decided to keep the offline version for itself (despite this, at least from my tests and for some languages, the Whisper voice recognition that I'm using has more or less the same quality as Google's).

Google only offers the possibility of using the Translation APIs offline and for free, but from my tests I have verified that their quality sucks and is much worse than Google Translate in offline mode (even if they say that the models used are the same).
