### ISSUE TITLE
[Feature request] Add Support for Irish Language

### ISSUE THREAD

**Issue by Alexanderkocha** [niedev/RTranslator#78]
Hi! I would like to first thank everyone who worked on this for developing this amazing app. I've got one small suggestion for something that might make the app more useful. 

-I've noticed the Irish language is supposed by the NLLB model, but isn't available as a low quality model in RTranslator. I've struggled to find another (close to) open source and/or private solution that supports the language offline. 

-I'm wondering if it were possible to include the language in a future release.

Thanks for your consideration

**Comment by niedev** [comment]
Thank you! In these days I'll check why I didn't add it and if I can I'll add it.

**Comment by Alexanderkocha** [comment]
That would be brilliant, thank you for looking into it so quickly!

**Comment by niedev** [comment]
The language is supported (but only from nllb, so only for the text translation), I must have skipped it by distraction 😅, thanks for pointing it out, I made a new release that now also supports Irish (2.1.1), let me know if it works well.

**Comment by Alexanderkocha** [comment]
Thank you! I'll be sure to test it as soon I've got the update installed.

**Comment by Alexanderkocha** [comment]
> I must have skipped it by distraction 😅
Haha, I guess even developers aren't immune to that :open_mouth: 


> let me know if it works well

The results seem good so far, considering this is a relatively niche language, with only a low-quality model available. All of which is very much out of the control of this project.

I'll drop a comment and re-open this issue if I find any serious issues with the output, however, it seems to be working perfectly from release.

Once again, many thanks for adding this language :D
