### ISSUE TITLE
How to use the onnx export file of the nllb model for inference

### ISSUE THREAD

**Issue by LiPengtao0504** [niedev/RTranslator#84]
There are three onnx export files for the nllb model: decoder_madel.onnx decoder_with_past_model.onnx  encoder_model.onnx ， How should I use these three files for reasoning？Do you have any code examples？

**Comment by niedev** [comment]
I'm sorry, but as I said in the other issue a tutorial on how to do the inference of these models would be very long, and at the moment I don't have much free time, you could read the source code of the app to understand a bit better how the inference works ([this](https://github.com/niedev/RTranslator/blob/v2.00/app/src/main/java/nie/translator/rtranslator/voice_translation/neural_networks/translation/Translator.java) to be precise), and do some research online.
