### ISSUE TITLE
[Feature request] Translate audio immediately

### ISSUE THREAD

**Issue by DarkTyger** [niedev/RTranslator#85]
Tried to use the app to translate from spoken English to audible Korean, without bluetooth headphones. Samsung Galaxy S10e running Android.

1. Download https://github.com/niedev/RTranslator/releases/tag/2.1.1
1. Install RTranslator_2.1.1.apk 
1. Run RTranslator
1. Install 1GB large language model.

Here, I selected English to Korean. 

**Expected**

* RTranslator opens and asks permission to use phone's microphone.
* RTranslator receives audio from microphone when I talk.
* RTranslator translates audio from phone from English to Korean.

**Actual**

RTranslator prompts me to insert text. RTranslator requires me to press Translate. This is not how I anticipated the application to behave. I don't want to type, I want to speak using the phone's microphone, then have the text be translated into Korean and spoken over the phone's speaker.

There are other issues, like after clicking Conversation mode and denying access, I can no longer go into Conversation mode ever again. That's not good. It should prompt me for access again when I press Conversation mode.

**Comment by DarkTyger** [comment]
In WalkieTalkie mode, English speech is translated directly into Korean text. There is no Korean TTS engine installed. If I select Korean as the target language, and there's no suitable TTS engine, is it possible for the software to prompt me to install one?

**Comment by niedev** [comment]
@DarkTyger The WalkieTalkie mode, as you probably discovered, is accessible by pressing the dedicated button on the main screen.

Also if you deny a permission Android apps cannot ask for it again (it does not depend on me, but on Android), to grant the permission again you have to go to the phone settings -> Applications -> RTranslator -> permissions -> location and allow (the location permission is needed to use Bluetoooth, I do not actually collect your location but Bluetooth could be used for this, for this reason Android requires that permission).

As for TTS [here](https://github.com/niedev/RTranslator/tree/v2.00?tab=readme-ov-file#text-to-speech) is explained how to install and select the right TTS (Google TTS should support Korean).
