### ISSUE TITLE
[Feature request]zip obb import

### ISSUE THREAD

**Issue by ghost** [niedev/RTranslator#86]
Thank you for wanting to share an idea! But before starting, ensure to check if this feature request respects the following requirements:
- [x] It is written in English (I can translate what you say, but issues written in English are easier to read for the other users).
- [x] There is not already a similar feature request among the open or closed issues.

**Is your feature request related to a problem? Please describe.**
GrapheneOS system cannot copy to "Android/data/nie.translator.rtranslator/files".

* Please provide zip obb import function

**Additional context**
![Screenshot_20241027-173346](https://github.com/user-attachments/assets/3be2531d-3abd-412a-8ffe-f80cb9dcda4a)

**Comment by niedev** [comment]
Hi @Zig-Rust-Odin, you can see this folder only if you connect the phone to a PC and you access that folder from the PC, please follow [this guide](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md) precisely to do sideloading.

**Comment by ghost** [comment]
> Hi @Zig-Rust-Odin, you can see this folder only if you connect the phone to a PC and you access that folder from the PC, please follow [this guide](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md) precisely to do sideloading.

Hi niedev
I don't have a PC.
Even with a PC, the [GrapheneOS](https://grapheneos.org/) system does not allow access to folders.

**Comment by niedev** [comment]
Ok, the normal download doesn't work?
