### ISSUE TITLE
[Offline TTS BUG]

### ISSUE THREAD

**Issue by IM-IMPO** [niedev/RTranslator#91]
Thank you for wanting to report a bug! But before starting, ensure to check if this bug report respects the following requirements:
- [ ✓] It is written in English (I can translate what you say, but issues written in English are easier to read for the other users).
- [ ✓] There is not already a similar bug report among the open issues (if this is the case you can leave a comment describing your problem in more detail in that already opened issue)

**Describe the bug**
I found out that the translated language doesn't output TTS when offline but when I tried it on text input it worked fine (this applies to almost all of the languages in apk except for English and Japanese which are working fine)

**Screen Record**

https://github.com/user-attachments/assets/6607b501-4c63-4e00-a63c-e7cbe309f67d

**Smartphone (please complete the following information):**
 - Device: [Vivo Y31]
 - Android OS version: [Android 13]
 - TTS used: [Google's TTS]
 - Version of the app: [2.1.2]

**Additional context**
The problem also applies to WalkieTalkie Mode and Conversation mode wherein the only working Translated TTS when offline is Japanese and English

**Comment by niedev** [comment]
So, if you switch the languages on the example with Chinese as the input language the tts works even in offline mode? And even changing the input phrase? (sometimes, with Google TTS, if a language has not been downloaded and a certain text is played when the phone is online then it works offline too, but if you change the text it should not work) If that is not the case and you are using Google TTS you can download a language for offline support by searching, in the settings of your phone, "offline speech recognition", from there you can download the language you need, from my tests this should solve the problem, even if TTS is not Speech recognition, it makes no sense (thanks to Google) but it should work, let me know.

**Comment by IM-IMPO** [comment]
@niedev, the solution works. we just need to download the voice data for a certain language, and it'll work properly even in offline
