### ISSUE TITLE
[Feature request] Suggest eSpeak and RHVoice as open-source TTS engines

### ISSUE THREAD

**Issue by lrq3000** [niedev/RTranslator#93]
For the phones where there is no or limited TTS engines (eg, phones without the Google Mobile Services GMS), a great alternative is espeak (https://github.com/espeak-ng/espeak-ng and https://f-droid.org/fr/packages/com.reecedunn.espeak/), which allows to have multilanguage TTS with very small packages, totally offline and open-source. Almost all languages supported by RTranslator are also supported by espeak, including low quality data languages, so it looks like a match made in heaven (and I tried personally, it works).

For those wanting higher quality mor natural sounding TTS, there is RHVoice, but it supports only a very limited number of supported languages for now: https://github.com/RHVoice/RHVoice

I suggest that RTranslator can mention and link to these projects, so that users who don't have an adequate multilingual TTS on their phone can try them.

**Comment by niedev** [comment]
Hi, thank you for the suggestion, in the next weeks I will test these TTS engines and if they have good quality, sure, I will mention those in the readme

**Comment by lrq3000** [comment]
RHVoice is awesome out of the box.

ESpeak is lower quality but it's there since a longer time so it has more languages covered and is using a tech with small languages files so it's easy to support tons of languages on a phone.

If you try eSpeak, i found that slowing down the speech speed was necessary, after it does not sound as natural as modern online tts models but it's largely intelligible.

**Comment by lrq3000** [comment]
Actually, here is a demo I just recorded on my phone so you can hear for yourself: https://www.youtube.com/shorts/VJgbFbQtBSI

**Comment by niedev** [comment]
Thanks for the video, I also downloaded and tested them and unfortunately the quality of eSpeak is really really low.
RHVoice has a good quality but supports very few languages, so I don't feel like recommending them in the readme, even if obviously anyone is free to use them. 
But if one day you find an open source TTS with the quality of RHVoice and with many supported languages ​​let me know, I'll be happy to include it in the readme.

**Comment by DiagonalArg** [comment]
SherpaTTS is the next step in these TTS engines.  See the request [here](https://github.com/niedev/RTranslator/issues/120).
