### ISSUE TITLE
翻译后能够重复播放翻译的结果

### ISSUE THREAD

**Issue by enjoyrose** [niedev/RTranslator#96]
The translated results can be played repeatedly. A small speaker is placed behind the results so that the translated results can be listened to repeatedly.
翻译后的结果能够重复播放，在结果后面放一个小喇叭，能够重复听翻译的结果。

**Comment by niedev** [comment]
I'm sorry but I didn't understand anything, even with a translator, please write your issue in English.

**Comment by enjoyrose** [comment]
The translated results can be played repeatedly. A small speaker is placed behind the results so that the translated results can be listened to repeatedly.

**Comment by niedev** [comment]
Ok, you mean [this feature](https://github.com/niedev/RTranslator/issues/95) right?

**Comment by enjoyrose** [comment]
> 好的，你是说[这个功能](https://github.com/niedev/RTranslator/issues/95)，对吧？

Yes, thank you very much for your hard work.
