### ISSUE TITLE
[Feature request] transcribe/translate local audio

### ISSUE THREAD

**Issue by mzltest** [niedev/RTranslator#97]
Thank you for wanting to share an idea! But before starting, ensure to check if this feature request respects the following requirements:
- [x] It is written in English (I can translate what you say, but issues written in English are easier to read for the other users).
- [x] There is not already a similar feature request among the open or closed issues.

***

Since everything is locally computed and batteries included, An option for transcribe/translate local audio file may be feasible and cost-effective(think whisper apis+llm translate apis pricing).

**Comment by mzltest** [comment]
* And if possible , export timed captions (might involve a VAD for segmenting)

**Comment by niedev** [comment]
Hi @mzltest, thank you for your suggestion, I've added this to the list of possible feature to include in the future (although it probably won't come very soon since I have little time to dedicate to the app at the moment and I prefer to focus on improving the features it already has).
